CAVE_SPIDER: 0.95
ELDER_GUARDIAN: 1.1
SILVERFISH: 0.8
PANDA: 0.5
ENDERMITE: 0.9
GIANT: 2.0
GHAST: 0.95
DOLPHIN: 0.75
DROWNED: 1.0
PUFFERFISH: 0.5
SLIME: 1.0
SHULKER: 1.05
BLAZE: 1.05
STRAY: 1.0
VINDICATOR: 1.1
SPIDER: 1.0
POLAR_BEAR: 0.75
EVOKER: 1.05
ENDERMAN: 1.1
SKELETON: 1.0
GUARDIAN: 1.0
VEX: 1.05
HOGLIN: 1.0
TRADER_LLAMA: 0.6
WITHER_SKELETON: 1.15
ZOGLIN: 1.0
IRON_GOLEM: 1.1
PIGLIN_BRUTE: 1.1
PHANTOM: 0.9
WITCH: 1.0
WARDEN: 2.0
PILLAGER: 1.1
PIGLIN: 1.0
ZOMBIE: 1.0
CREEPER: 0.8
MAGMA_CUBE: 1.0
ZOMBIFIED_PIGLIN: 0.9
HUSK: 1.0
SHULKER_BULLET: 1.05
BREEZE: 1.05
RAVAGER: 1.2
BEE: 0.5
