#中立、敌对物数值倍率调整，以1为基准,小于1的数值代表削弱，大于1的数值代表加强
BEE: 0.5
BLAZE: 1.2
BREEZE: 1.1
CAVE_SPIDER: 0.9
DROWNED: 1.0
DOLPHIN: 0.7
ELDER_GUARDIAN: 1.3
ENDERMAN: 1.2
ENDERMITE: 0.9
EVOKER: 1.2
GIANT: 2.5
GHAST: 0.9
GUARDIAN: 1.0
HOGLIN: 1.1
HUSK: 1.0
IRON_GOLEM: 1.4
MAGMA_CUBE: 1.0
PANDA: 0.5
PHANTOM: 0.8
PIGLIN: 1.1
PIGLIN_BRUTE: 1.2
POLAR_BEAR: 0.7
PUFFERFISH: 0.5
RAVAGER: 1.4
SHULKER: 1.1
SHULKER_BULLET: 1.1
SKELETON: 1.0
SLIME: 1.0
SPIDER: 1.0
STRAY: 1.0
VEX: 1.1
VINDICATOR: 1.2
WARDEN: 2.5
WITCH: 1.0
ZOGLIN: 1.0
ZOMBIE: 1.0
ZOMBIFIED_PIGLIN: 0.9

#计算玩家数值时的参考
#玩家生命值权重
health-rate: 6
#玩家盔甲权重
armor-rate: 4

#玩家伤害吸收值折算为生命值的比率
#0.5表示玩家拥有20生命值，10伤害吸收值的时候，最终生命值按照20+10*0.5 = 30计算
absorption-rate: 0.7

#连锁仇恨配置
#是否启用连锁仇恨
chain-enabled: true
#连锁仇恨的最大数量
count: 5
#连锁仇恨的最大范围(x,y,z)
range: 5

#怪物行为配置
#是否允许怪物放置方块
can-place-block: true
#是否允许怪物破坏方块
can-break-block: true
